config/routes.rb
Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/dashboard', to: 'dashboard#index'

  namespace :manager do
    resources :employees, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :employees, only: [:index, :show, :edit, :update]
  end

  namespace :hr do
    resources :employees, only: [:index, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_secure_password

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true

  has_many :supervisees, class_name: "Employee",
                          foreign_key: "manager_id"

  belongs_to :manager, class_name: "Employee", optional: true

  enum role: ['default', 'hr_employee', 'manager', 'admin']

  def self.all_except_hr
    where.not(department: 'Human Resources' )
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin
end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < Admin::BaseController
  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to admin_employee_path(@employee), notice: "Employee was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def employee_params
    params.require(:employee).permit(:name, :email, :salary, :annual_bonus, :vacation_balance, :department, :role)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_employee, :current_manager?, :current_admin?, :current_hr_employee?

  def current_employee
    @current_employee ||= Employee.find(session[:employee_id]) if session[:employee_id]
  end

  def current_manager?
    current_employee && current_employee.manager?
  end

  def current_admin?
    current_employee && current_employee.admin?
  end

  def current_hr_employee?
    current_employee && current_employee.hr_employee?
  end

  def require_employee
    render file: 'public/404', status: :not_found unless current_employee
  end

  def require_manager
    render file: 'public/404', status: 404 unless current_manager?
  end

  def require_admin
    render file: 'public/404', status: 404 unless current_admin?
  end

  def require_hr_employee
    render file: 'public/404', status: 404 unless current_hr_employee?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_employee

  def index
    @employee = Employee.find(current_employee.id)
  end
end

app/controllers/hr/base_controller.rb
class Hr::BaseController < ApplicationController
  before_action :require_hr_employee
end

app/controllers/hr/employees_controller.rb
class Hr::EmployeesController < Hr::BaseController
  def index
    @employees = Employee.all_except_hr
  end

  def show
    @employee = Employee.find(params[:id])
  end
end

app/controllers/manager/base_controller.rb
class Manager::BaseController < ApplicationController
  before_action :require_manager
end

app/controllers/manager/employees_controller.rb
class Manager::EmployeesController < Manager::BaseController
  def index
    @employees = current_employee.supervisees
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to manager_employee_path(@employee), notice: "Employee was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def employee_params
    params.require(:employee).permit(:name, :email, :salary, :annual_bonus, :vacation_balance, :department)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    employee = Employee.find_by(email: params[:email])
    if employee && employee.authenticate(params[:password])
      session[:employee_id] = employee.id
      flash[:notice] = "Welcome, #{employee.name}!"
      redirect_to '/dashboard'
    else
      flash[:notice] = 'Your email or password was incorrect!'
      redirect_to '/'
    end
  end

  def destroy
    session.delete(:employee_id)
    flash[:success] = 'You have been logged out.'
    redirect_to '/'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/employees/_form.html.erb
<%= form_with(model: [:admin, employee], local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.number_field :salary %>
  </div>

  <div class="field">
    <%= form.label :annual_bonus %>
    <%= form.number_field :annual_bonus %>
  </div>

  <div class="field">
    <%= form.label :vacation_balance %>
    <%= form.text_field :vacation_balance %>
  </div>

  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.select :role, options_for_select(["default", "hr_employee", 'manager', 'admin']) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/employees/edit.html.erb
<h1>Edit Employee</h1>

<%= render 'form', employee: @employee %>

app/views/admin/employees/index.html.erb
<h1>All Employees</h1>

<ul>
  <% @employees.each do |employee| %>
    <li>
      <p><%= employee.name %></p>
      <p><%= link_to 'View details', admin_employee_path(employee.id) %></p>
    </li>
  <% end %>
</ul>

app/views/admin/employees/show.html.erb
<h1><%= @employee.name %>'s Dashboard</h1>

<p>Email: <%= @employee.email %></p>
<p>Salary: $<%= @employee.salary %></p>
<p>Annual Bonus: $<%= @employee.annual_bonus %></p>
<p>Vacation Balance: <%= @employee.vacation_balance %> hours</p>
<p>Department: <%= @employee.department %></p>
<% if @employee.manager %>
  <p>Manager: <%= @employee.manager.name %></p>
<% end %>
<p>Role: <%= @employee.role %></p>
<p><%= link_to "Edit", edit_admin_employee_path(@employee.id) %></p>

app/views/dashboard/index.html.erb
<h1><%= @employee.name %>'s Dashboard</h1>

<p>Email: <%= @employee.email %></p>
<p>Salary: $<%= @employee.salary %></p>
<p>Annual Bonus: $<%= @employee.annual_bonus %></p>
<p>Vacation Balance: <%= @employee.vacation_balance %> hours</p>
<p>Department: <%= @employee.department %></p>

<% if @employee.manager %>
  <p>Manager: <%= @employee.manager.name %></p>
<% end %>

<% if current_manager? %>
  <%= link_to 'View Supervisees', manager_employees_path %>
<% end %>

<% if current_admin? %>
  <%= link_to 'View All Employees', admin_employees_path %>
<% end %>

app/views/hr/employees/index.html.erb
<h1>All Non-HR Employees</h1>

<ul>
  <% @employees.each do |employee| %>
    <li>
      <p><%= employee.name %></p>
      <p><%= link_to 'View details', hr_employee_path(employee.id) %></p>
    </li>
  <% end %>
</ul>

app/views/hr/employees/show.html.erb
<h1><%= @employee.name %>'s Dashboard</h1>

<p>Email: <%= @employee.email %></p>
<p>Salary: $<%= @employee.salary %></p>
<p>Annual Bonus: $<%= @employee.annual_bonus %></p>
<p>Vacation Balance: <%= @employee.vacation_balance %> hours</p>
<p>Department: <%= @employee.department %></p>
<% if @employee.manager %>
  <p>Manager: <%= @employee.manager.name %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeHub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <% if current_employee %>
        <p><%= link_to "Logout", "/logout" %></p>
      <% end %>
    </nav>

    <% flash.each do |type, message| %>
      <p><%= message %></p>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/manager/employees/_form.html.erb
<%= form_with(model: [:manager, employee], local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.number_field :salary %>
  </div>

  <div class="field">
    <%= form.label :annual_bonus %>
    <%= form.number_field :annual_bonus %>
  </div>

  <div class="field">
    <%= form.label :vacation_balance %>
    <%= form.text_field :vacation_balance %>
  </div>

  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/manager/employees/index.html.erb
<h1><%= current_employee.name %>'s Supervisees</h1>

<ul>
  <% @employees.each do |supervisee| %>
    <li>
      <p><%= supervisee.name %></p>
      <p><%= link_to 'View details', manager_employee_path(supervisee.id) %></p>
    </li>
  <% end %>
</ul>

app/views/manager/employees/show.html.erb
<h1><%= @employee.name %>'s Dashboard</h1>

<p>Email: <%= @employee.email %></p>
<p>Salary: $<%= @employee.salary %></p>
<p>Annual Bonus: $<%= @employee.annual_bonus %></p>
<p>Vacation Balance: <%= @employee.vacation_balance %> hours</p>
<p>Department: <%= @employee.department %></p>
<% if @employee.manager %>
  <p>Manager: <%= @employee.manager.name %></p>
<% end %>
<p><%= link_to "Edit", edit_manager_employee_path(@employee.id) %></p>

app/views/welcome/index.html.erb
<h1>Welcome to Employee Hub</h1>

<p>Log in to view your employee information.</p>

<%= form_tag '/login' do %>
  <%= label_tag :email %>
  <%= email_field_tag :email, nil, placeholder: 'Email' %>

  <%= label_tag :password %>
  <%= password_field_tag :password, nil, placeholder: 'Password' %>

  <%= submit_tag "Login" %>
<% end %>